TestingStudentKnowledge/TSKApp/Controllers/StatisticController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TSKApp.BLL;
using TSKApp.DAL.Models;
using TSKApp.PL;
using TSKApp.PL.Models;

namespace TSKApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StatisticController : Controller
    {
        private readonly ILogger<StatisticController> _logger;
        private readonly DataManager _dataManager;
        private readonly ServicesManager _serviceManager;
        private readonly UserManager<AppUser> _userManager;

        public StatisticController(ILogger<StatisticController> logger, DataManager dataManager,
            UserManager<AppUser> userManager)
        {
            _logger = logger;
            _dataManager = dataManager;
            _serviceManager = new ServicesManager(_dataManager);
            _userManager = userManager;
        }

        // GET
        public IActionResult Index(int testId)
        {
            //List<TestViewModel> model = _serviceManager.Tests.GetTestsList().Where(x=>x.User.Id == _userManager.FindByEmailAsync(User.Identity.Name).Result.Id).ToList();
            List<StatisticModel> model = _serviceManager.Statistics.GetAllByTestId(testId);
            return View(model);
        }
    }
}

TestingStudentKnowledge/TSKApp/Controllers/TestController.cs
namespace TSKApp.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Newtonsoft.Json;
    using TSKApp.BLL;
    using TSKApp.DAL.Models;
    using TSKApp.PL;
    using TSKApp.PL.Models;
    using static TSKApp.Enums.Helpers;

    public class TestController : Controller
    {
        private readonly ILogger<TestController> _logger;
        private readonly DataManager _dataManager;
        private readonly ServicesManager _serviceManager;
        private readonly UserManager<AppUser> _userManager;
        private IHttpContextAccessor _httpContextAccessor;

        public TestController(ILogger<TestController> logger, DataManager dataManager, UserManager<AppUser> userManager, IHttpContextAccessor httpContextAccessor)
        {
            _logger = logger;
            _dataManager = dataManager;
            _serviceManager = new ServicesManager(_dataManager);
            _userManager = userManager;
            _httpContextAccessor = httpContextAccessor;
        }
        /*public IActionResult Index()
        {
            return View();
        }*/

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult MyTests(string error = null)
        {
            ViewBag.AllowError = error;
            var tests = _serviceManager.Tests.GetTestsList();
            return View(tests);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [Route("/Test/Delete/{Id:int}")]
        public IActionResult Delete(int Id)
        {
            _serviceManager.Tests.RemoveTestById(Id);
            return Ok();
        }
        
        [HttpGet]
        [Authorize(Roles = "Student")]
        public async Task<IActionResult> TestPassed(int totalMarks)
        {
            List<CorrectAnswerEditModel> rememberPreviousQuestionResult = _httpContextAccessor.HttpContext.Session.Get<List<CorrectAnswerEditModel>>("ListOfQuestionsResult");
            _httpContextAccessor.HttpContext.Session.Remove("ListOfQuestionsResult");

            var testId = rememberPreviousQuestionResult[0].TestId;
            var test = _serviceManager.Tests.GetTestById(testId);
            
            AppUser user = await _userManager.FindByEmailAsync(User.Identity.Name);
            StatisticModel statModel = new StatisticModel(){ Test = test, User = user, Result = totalMarks };
            _serviceManager.Statistics.SetIntoDb(statModel);

            _serviceManager.UserTestAccess.RemoveAccessByUserIdAndTestId(user.Id, testId);
            
            ViewBag.TotalMarks = totalMarks;
            ViewBag.TestId = testId; //not used
            ViewBag.TestTitle = test.Name;
            
            var models = _serviceManager.CorrectAnswers.GetModelsFromEditToView(rememberPreviousQuestionResult);
            return View(models);
        }

        [HttpGet]
        [Authorize(Roles = "Student")]
        public IActionResult TestPassing(int testId, int questionIndex = 0, int totalMarks = 0)
        {
            var questions = _serviceManager.Questions.GetQuestionsByTestId(testId);

            //For remember prev questions result
            List<CorrectAnswerEditModel> rememberPreviousQuestionResult = _httpContextAccessor.HttpContext.Session.Get<List<CorrectAnswerEditModel>>("ListOfQuestionsResult") ?? new List<CorrectAnswerEditModel>();

            ViewBag.TotalMarks = totalMarks;
            if (questionIndex > questions.Count - 1)
            {
                return RedirectToAction("TestPassed", new { totalMarks, rememberPreviousQuestionResult });
            }

            _httpContextAccessor.HttpContext.Session.Set("ListOfQuestionsResult", rememberPreviousQuestionResult);

            var testTitle = _serviceManager.Tests.GetTestById(testId).Name;
            var currentQuestion = questions[questionIndex];
            ViewBag.testId = testId;
            ViewBag.Questions = questions;
            ViewBag.CurrentQuestion = questionIndex + 1;
            ViewBag.QuestionIndex = questionIndex;
            ViewBag.TestTitle = testTitle;

            return View(currentQuestion);
        }

        [HttpPost]
        [Authorize(Roles = "Student")]
        public RedirectToActionResult TestPassingAct(int testId, int questionId, int answerId, int questionIndex, int totalMarks, TestPassingActions actionType/*, List<CorrectAnswerEditModel> rememberPreviousQuestionResult*/)
        {
            var rememberPreviousQuestionResult = _httpContextAccessor.HttpContext.Session.Get<List<CorrectAnswerEditModel>>("ListOfQuestionsResult");
            switch (actionType)
            {
                case TestPassingActions.NextQuestion:
                    bool correct = _serviceManager.CorrectAnswers.GetCorrectPropertyByQuestionAndAnswerIds(questionId, answerId);
                    totalMarks = correct ? totalMarks + 1 : totalMarks;
                    rememberPreviousQuestionResult.Add(new CorrectAnswerEditModel() { TestId = testId, QuestionId = questionId, AnswerId = answerId, Correct = correct });
                    _httpContextAccessor.HttpContext.Session.Set("ListOfQuestionsResult", rememberPreviousQuestionResult);
                    questionIndex++;
                    break;
                default:
                    //Maybe use in future
                    break;
            }
            return RedirectToAction("TestPassing", new { testId, questionIndex, totalMarks });
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult CreateTest()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Student")]
        public IActionResult BeginTestPassing(int testId, string title)
        {
            ViewBag.testId = testId;
            ViewBag.Title = title;
            TestViewModel model = _serviceManager.Tests.GetTestById(testId);
            return View(model);
        }

        [HttpGet]
        [Route("/Allow/{id}")]
        [Authorize(Roles = "Admin")]
        public IActionResult Allow(int id)
        {
            ViewBag.testId = id;
            return PartialView("_AllowStudentPartial");
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Allow(int testId, string email)
        {
            var user = await _userManager.FindByEmailAsync(email);
            string error = null;
            if (user == null)
            {
                error = "Student not found"; 
            }
            else
            {
                _serviceManager.UserTestAccess.SetAllow(testId, user.Id);
            }
            return RedirectToAction("MyTests", new { error = error });
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public RedirectToActionResult CreateTest(TestEditModel _model)
        {
            string adminName = User.Identity.Name;
            int testId = _serviceManager.Tests.SetTestEditModelIntoDb(_model, adminName);
            return RedirectToAction("StartCreateQuestion", new { testId });
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult StartCreateQuestion(int testId)
        {
            //ViewBag.testId = testId;
            var _Model = new QuestionEditModel();
            _Model.Id = testId;
            return View(_Model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult StartCreateQuestion(QuestionEditModel _model, Actions actionType, int removingAnswerId)
        {
            int truthCheckCounter = 0;
            foreach (var prop in _model.AnswerEditModels)
            {
                if (prop.Correct)
                {
                    truthCheckCounter++;
                }
                if (truthCheckCounter > 1)
                {
                    ModelState.AddModelError("Truth answers greater then 1", "There can be only one correct answer");
                    return View(_model);
                }
            }
            //this.ViewBag.testId = testId;
            //_model.Id = testId;
            switch (actionType)
            {
                case Actions.MoreQuestion:
                    if (truthCheckCounter == 0)
                    {
                        ModelState.AddModelError("Correct not selected", "The correct answer is not selected");
                        return View(_model);
                    }
                    _serviceManager.Questions.SaveQuestionEditModelIntoDb(_model);
                    _model = new QuestionEditModel() { Id = _model.Id };
                    ModelState.Clear();
                    break;
                case Actions.MoreAnswer:
                    _model.AnswerEditModels.Add(new AnswerEditModel());
                    break;
                case Actions.RemoveAnswer:
                    AnswerEditModel _answerToDelete = _model.AnswerEditModels[removingAnswerId];
                    if (_model.AnswerEditModels.Count > 1)
                    {
                        _model.AnswerEditModels.Remove(_answerToDelete);
                        ModelState.Clear();
                    }
                    break;
                case Actions.End:
                    if (truthCheckCounter == 0)
                    {
                        ModelState.AddModelError("Correct not selected", "The correct answer is not selected");
                        return View(_model);
                    }
                    _serviceManager.Questions.SaveQuestionEditModelIntoDb(_model);
                    //return RedirectToAction("EndCreating", new { testId=_model.Id });
                    return RedirectToAction("MyTests");
                    break;
                default:

TestingStudentKnowledge/TSKApp/Views/Test/BeginTestPassing.cshtml
@using TSKApp.PL.Models
@using Microsoft.CodeAnalysis
@model TestViewModel
    <style>
        .form {
            margin: 50px auto;
            width: 700px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .form__title {
            font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            margin-bottom: 40px;
            font-size: 25px;
            width: 100%;
            line-height: 90px;
            text-align: center;
            color: #fff;
            background-color: #37346b
        }
    </style>
    <div class="d-flex justify-content-center">
        <div style="margin-top: 35px; width:700px">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-center">
                        <h4>@Model.Name</h4>
                    </div>
                </div>
                <div class="card-body">
                    <div>
                        <div class="d-flex justify-content-center">
                            <div>
                                <h4>@Model.User.FirstName @Model.User.LastName</h4>
                                <div class="d-flex justify-content-center">
                                    <img style='width:120px; height:120px; border-radius: 80px; margin-right: 20px' src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.User.Avatar))"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center">
                        <h4>Pass to:&nbsp;@Model.PassToDate.Day/@Model.PassToDate.Month/@Model.PassToDate.Year</h4>
                    </div>
                    <div class="d-flex justify-content-center" style="margin-top: 10px">
                        <a class="btn btn-success" asp-action="TestPassing" asp-route-testId=@ViewBag.testId style="/*background-color:#6c44db;*/ color:white; width:150px;">Attemp</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

TestingStudentKnowledge/TSKApp/Views/Test/CreateTest.cshtml
@using TSKApp.PL.Models
@model TestEditModel


<div class="d-flex justify-content-center" style="margin-top: 55px">
    <div class="card" style="width: 550px">
        <div class="card-header">
            <div>
                <div>
                    <h2 style="color:#6310CB;">Create Test</h2>
                </div>
            </div>
        </div>
        <form asp-action="CreateTest" class="form" method="post">
            <div class="card-body">

                <div>
                    <div>
                        <div>
                            <label class="form-check-label">Title</label>
                            @Html.TextBoxFor(model => model.Name, new {@class = "form-control", placeholder = "Input title"})
                        </div>
                        <div style="margin-bottom: 10px">
                            <div style="margin-top: 20px;">
                                <label class="form-check-label">Pass to</label>
                                <div>
                                    @Html.TextBoxFor(model => model.PassToDate, new {@class = "form-control", placeholder = "number", type = "date"})
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-center mt-3">
                    <div>
                        <button class="btn" style="color: white; background: #6863ca; width: 150px" type="submit">Create</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

        
   

TestingStudentKnowledge/TSKApp/Views/Test/EndCreating.cshtml
<div>
    <div>
        <h1>TEST WAS CREATED</h1>
    </div>
</div>

TestingStudentKnowledge/TSKApp/Views/Test/MyTests.cshtml
@using TSKApp.PL.Models
@model List<TestViewModel>
    <style>
        .form {
            margin: 50px auto;
            width: 700px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .form__container {
            width: 275px;
            display: flex;
            flex-direction: column;
        }

        .form__title {
            font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
            margin-bottom: 40px;
            font-size: 25px;
            width: 100%;
            line-height: 90px;
            text-align: center;
            color: #fff;
            background-color: #37346b
        }


        .form-control {
            border-radius: 25px;
        }

        .form__button {
            margin-top: -7px;
            display: inline-block;
            color: #ffffff;
            border-radius: 25px;
            font-family: Verdana;
            width: auto;
            height: auto;
            font-size: 16px;
            padding: 10px 58px;
            background: #6863ca;
            border: 0;
        }

        .form__buttona {
            margin-top: -20px;
            display: inline-block;
            color: #ffffff;
            border-radius: 30px;
            font-family: Verdana;
            width: auto;
            height: auto;
            font-size: 16px;
            padding: 5px 40px;
            background: #614C6F;
            border: 0;
        }

            .form__button:hover, .form__button:active {
                color: #ffffff;
                background: #37346b;
            }
        .form__buttona:hover, .form__buttona:active {
            color: #ffffff;
            background: #37346b;
        }

        .form__text {
            font-size: 12px;
        }

        p {
            margin-top: 10px;
        }

        .form_link {
            margin-top: -10px;
        }
    </style>
    <div class="">
        <div class="row pt-4">
            <div class="col-6">
                <h2 style="color:#6310CB;">Tests</h2>
            </div>
        </div>
        @*<h2 class="form__title">Create test</h2>*@
        <div id="ShowModalHere"></div>
        <div class="deleteArea">
            @if ((string)ViewBag.AllowError != null)
            {
                <span class="text-danger">Student not found</span>
            }
            @if (Model.Count > 0)
            {
                <table class="table table-bordered table-striped" style="width: 100%">
                    <thead>
                    <tr>
                        <th>
                            Test
                        </th>
                        <th>
                            Created At                        
                        </th>
                        <th>
                        </th>
                    </tr>
                    </thead>
                <tbody id="table-body-area">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td width="">@item.Name</td>
                                <td class="text-center" width="">@item.Created</td>
                                <td class="text-center" width="">
                                    <div>
                                        <button class="btn btn-primary" data-toggle="ajax-modal" data-target="#allowStudent" data-url="/Allow/@item.Id">Allow</button>
                                        <a class="btn btn-success" asp-controller="Statistic" asp-action="Index" asp-route-testId="@item.Id">Statistic</a>
                                        <button class="btn btn-danger js-delete" data-Id="@item.Id">Delete</button>
                                    </div>
                            </td>
                        </tr>
                            @*<a class="d-flex" asp-action="TestPassing" asp-route-testId=@item.Id style="margin-right: 30px">*@
                    }
                    </tbody>
                </table>
            }
            else
            {
                <div style="margin-top: 150px;">
                    <span><b>Tests is empty</b></span>
                </div>
            }
        </div>
        <div>
            <a class="form__button" href="/Test/CreateTest">Create</a>
        </div>
    </div>

@section Scripts
{
    <script src="~/js/actions.js"></script>
}

TestingStudentKnowledge/TSKApp/Views/Test/StartCreateQuestion.cshtml
@using static TSKApp.Enums.Helpers 
@using TSKApp.PL.Models
@model QuestionEditModel
   
<div>
    <div class="d-flex justify-content-center" style="margin-top: 40px">
        <div class="card" style="width: 550px">
            <div class="card-header">
                <div>
                    <div>
                        <h2 style="color:#6310CB;">Create Questions</h2>
                    </div>
                </div>
            </div>
            <form asp-controller="Test" asp-action="StartCreateQuestion" class="form" method="post">
                @*<input type="hidden" asp-for="Id" style="margin-bottom: 20px;"/>*@
                <div class="card-body">
                    @Html.HiddenFor(model => model.Id)
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div style="margin-bottom: 20px;">
                        @Html.TextBoxFor(model => model.Name, new {@class = "form-control", placeholder = "Input question"})
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div>
                        @{ int AnswerInputs = Model.AnswerEditModels != null ? Model.AnswerEditModels.Count : 1; }
                        @foreach (var item in Enumerable.Range(0, AnswerInputs))
                        {
                            <div style="margin-bottom: 10px">
                                <div class="d-flex">
                                    <div>
                                        <div class="d-flex" style="    margin-right: 5px;">
                                            @Html.CheckBoxFor(model => model.AnswerEditModels[item].Correct, new {value = "true", style = "margin-right: 5px;margin-top: 12px;"})
                                            @Html.TextBoxFor(model => model.AnswerEditModels[item].Name, new {@class = "form-control", placeholder = "Input answer"})
                                        </div>
                                        <div>
                                            <span asp-validation-for="AnswerEditModels[item].Name" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="d-flex flex-row-reverse" style="margin-top: 10px; ">
                                        <div>
                                            <button class="btn btn-danger" type="submit" style="margine-left: 100px; margin-top: -10px;" asp-route-actionType=@Actions.RemoveAnswer asp-route-removingAnswerId=@item>Remove</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                    <div style="margin-top: 40px">
                        <div class="d-flex flex-xl-row-reverse justify-content-center">
                            <div class="d-flex flex-row-reverse">
                                <button class="btn btn-success" type="submit" asp-route-actionType=@Actions.MoreQuestion>New Question</button>
                            </div>
                            <div>
                                <button class="btn btn-warning" type="submit" style="margin-right: 10px" asp-route-actionType=@Actions.MoreAnswer>More Answer</button>
                            </div>
                        </div>
                    </div>
                    <div style="margin-top: 15px">
                    </div>
                </div>
                <div class="card-footer d-flex justify-content-center">
                    <button class="btn" type="submit" style="width: 458px; background: #6310CB; color:  white;" asp-route-actionType=@Actions.End>Finish</button>
                </div>

            </form>
        </div>
    </div>
</div>

    

@section Scripts
{ 
    <partial name="_ValidationScriptsPartial"></partial>
}

TestingStudentKnowledge/TSKApp/Views/Test/TestPassed.cshtml
@using TSKApp.PL.Models
@model List<CorrectAnswerViewModel>

<div class="d-flex justify-content-center" style="margin-top: 75px;">
    <div>

        <div class="card" style="width: 700px;">
            <div class="card-header">
                <div class="d-flex justify-content-center">
                    <div>
                        <h4>@ViewBag.TestTitle</h4>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div>
                    <h4>Total marks: @ViewBag.TotalMarks</h4>
                </div>
                <hr />
                <div>
                    <div class="card">
                        @foreach (var question in Model)
                        {
                            <div class="card-body">
                                <div class="d-flex">
                                    <span>@question.QuestionName</span>&nbsp;
                                    <div>
                                        @if (question.Correct)
                                        {<i class="fas fa-check" style="color: green"></i>
                                        }
                                        else
                                        {
                                            <i class="fas fa-times" style="color: red"></i>
                                        }
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <div class="card-footer" style="margin-top: 20px;">
                <div class="d-flex justify-content-center" >
                    <div>
                        <a class="btn" style="background-color:#6c44db; color: white" href="/">Back to main</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TestingStudentKnowledge/TSKApp/Views/Test/TestPassing.cshtml
@using static TSKApp.Enums.Helpers
@using TSKApp.PL.Models
@model QuestionViewModel

<div class="d-flex justify-content-center">
    <div class="d-flex justify-content-around" style="margin-top: 40px">
        @functions
        {
            public int Amount()
            {
                int counter = 1; 
                foreach (var question in ViewBag.Questions)
                {
                    counter++;
                }
                return counter;
            }
        }
        <form asp-controller="Test" asp-action="TestPassingAct" method="post">
            <div>
                <div class="d-flex justify-content-between" style="margin-bottom: 10px">
                    <div class="row pt-3">
                        <div class="col-6">
                            <h3 style="color:#6310CB;">@ViewBag.TestTitle</h3>
                        </div>
                    </div>
                    <h6 style="padding-top: 30px">Marked out of 1.00</h6>
                </div>
                <div class="card" style="width: 700px">
                    <div class="card-body">
                        <div>
                            <div>
                                <h5 style="margin-bottom: 15px">"@Model.Name"</h5>
                                <input type="hidden" name="testId" value="@ViewBag.testId"/>
                                <input type="hidden" name="questionId" value="@Model.Id"/>
                                <input type="hidden" name="questionIndex" value="@ViewBag.QuestionIndex"/>
                                <input type="hidden" name="totalMarks" value="@ViewBag.TotalMarks"/>
                                <div class="card">
                                    <div class="card-body" style="background-color: rgba(0,0,0,.03);">
                                        @foreach (var answer in Model.AnswerViewModels)
                                        {
                                            <div class="d-flex" style="margin-top: 10px;padding-left: 20px;">
                                                <input type="radio" name="answerId" value="@answer.Id" style="margin-top: 7px;"/>
                                                <p style="margin-left: 20px;">@answer.Name</p>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="d-flex flex-row-reverse" style="margin-top: 20px">
                    <button class="btn" type="submit" name="actionType" value=@TestPassingActions.NextQuestion style="font-size: 17px; background-color: #37346b; color: white;">Next question ></button>
                </div>
            </div>
        </form>
        <div/>
    </div>
</div>

TestingStudentKnowledge/TSKApp/Views/Test/_AllowStudentPartial.cshtml
<div class="modal fade" id="allowStudent">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="allowEmployee">Allow student</h4>
                <button type="button" class="close" data-dismiss="modal"><span>x</span></button>
            </div>
            <div class="modal-body">
                <form action="Allow" method="post">
                    <div class="form-group">
                        <input type="hidden" name="testId" value="@ViewBag.testId"/>
                        <label>Email</label>
                        <input class="form-control" name="email"/>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-save="modal">Done</button>
            </div>
        </div>
    </div>
</div>